name: dragon_quest
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  characters: ^1.3.0
  csv: ^5.0.2
  http: ^1.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.5
  lints: ^2.0.0
  test: ^1.21.0
